# vim:set ft=tmux:

# --> Catppuccin (ANSI)
set -ogq @thm_bg "terminal"
set -ogq @thm_fg "terminal"

# Colors
set -ogq @thm_rosewater "colour11"
set -ogq @thm_flamingo "colour13"
set -ogq @thm_pink "colour5"
set -ogq @thm_mauve "colour5"
set -ogq @thm_red "colour9"
set -ogq @thm_maroon "colour9"
set -ogq @thm_peach "colour1"
set -ogq @thm_yellow "colour3"
set -ogq @thm_green "colour2"
set -ogq @thm_teal "colour14"
set -ogq @thm_sky "colour10"
set -ogq @thm_sapphire "colour6"
set -ogq @thm_blue "colour12"
set -ogq @thm_lavender "colour4"

# Surfaces and overlays
set -ogq @thm_subtext_1 "colour7"
set -ogq @thm_subtext_0 "colour15"
set -ogq @thm_overlay_2 "colour15"
set -ogq @thm_overlay_1 "colour15"
set -ogq @thm_overlay_0 "colour8"
set -ogq @thm_surface_2 "colour8"
set -ogq @thm_surface_1 "colour0"
set -ogq @thm_surface_0 "colour0"
set -ogq @thm_mantle "colour0"
set -ogq @thm_crust "colour0"
